branch-defaults:
  default:
    environment: flask-aws-storybook
    group_suffix: null
global:
  application_name: storybook
  branch: null
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
